### ISSUE TITLE
We need new transform algorithm

### ISSUE THREAD

**Issue by MaoJianwei** [hiwanz/wgs2mars.js#2]
data at 2015.10.11

NMEA from GPS source：
lat = 39.5768506
lon = 116.2097481

Real Location (From 1. android API 2. picked by BaiduMap)：
lat = 39.96165504
lon = 116.35180069

If you have any improvement,
Please contact me @ maojianwei2016@126.com
Thank you very much !

**Comment by hiwanz** [comment]
我记得百度用的是自己的混淆算法，如果你是用百度地图sdk得到的坐标直接用sdk标记就可以了，不需要自己实现纠偏，之前实现这个是因为高德没有提供raw转换，现在高德也有转换接口了。
